In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df.head()

      name  age  salary department  bonus  salary_after_bonus salary_level
0  mahmoud   26  9000.0         it    600              9600.0         High
1    ahmed   24  8000.0         it    700              8700.0         High
2  mohamed   22  5000.0         hr    500              5500.0          Low
3      ali   32  4700.0    finance    400              5100.0          Low
4    samir   30  6675.0         hr    300              6975.0          Low

In [3]:
def increase_salary(x):
    return x * 1.10

df['salary'] = df['salary'].apply(increase_salary)
print(df)

      name  age  salary department  bonus  salary_after_bonus salary_level
0  mahmoud   26  9900.0         it    600              9600.0         High
1    ahmed   24  8800.0         it    700              8700.0         High
2  mohamed   22  5500.0         hr    500              5500.0          Low
3      ali   32  5170.0    finance    400              5100.0          Low
4    samir   30  7342.5         hr    300              6975.0          Low

In [4]:
df["salary_after_bonus"] = df["salary"] + df["bonus"]

In [5]:
print(df)

      name  age  salary department  bonus  salary_after_bonus salary_level
0  mahmoud   26  9900.0         it    600             10500.0         High
1    ahmed   24  8800.0         it    700              9500.0         High
2  mohamed   22  5500.0         hr    500              6000.0          Low
3      ali   32  5170.0    finance    400              5570.0          Low
4    samir   30  7342.5         hr    300              7642.5          Low

In [6]:
df['level'] = df['age'].apply(
    lambda x: 'senior' if x>=30 else 'junior'
)

In [7]:
df.head()

,name,age,salary,department,bonus,salary_after_bonus,salary_level,level
0,mahmoud,26,9900.0,it,600,10500.0,High,junior
1,ahmed,24,8800.0,it,700,9500.0,High,junior
2,mohamed,22,5500.0,hr,500,6000.0,Low,junior
3,ali,32,5170.0,finance,400,5570.0,Low,senior
4,samir,30,7342.5,hr,300,7642.5,Low,senior

In [12]:
df['name'] = df['name'].str.capitalize()
df['department'] = df['department'].str.upper()

In [13]:
df.head()

,name,age,salary,department,bonus,salary_after_bonus,salary_level,level
0,Mahmoud,26,9900.0,IT,600,10500.0,High,junior
1,Ahmed,24,8800.0,IT,700,9500.0,High,junior
2,Mohamed,22,5500.0,HR,500,6000.0,Low,junior
3,Ali,32,5170.0,FINANCE,400,5570.0,Low,senior
4,Samir,30,7342.5,HR,300,7642.5,Low,senior

In [14]:
df.to_csv('data.csv')