In [25]:
import pandas as pd

In [26]:
data = {
    'name' : ['ahmed','mohamed','mahmoud','ali','samir'],
    'age' : [24,22,26,32,30],
    'salary' : [8000,5000,9000,4700,None],
    'department' : ['it','hr','it','finance','hr']
}

df = pd.DataFrame(data)
df.head()

      name  age  salary department
0    ahmed   24  8000.0         it
1  mohamed   22  5000.0         hr
2  mahmoud   26  9000.0         it
3      ali   32  4700.0    finance
4    samir   30     NaN         hr

In [27]:
df.to_csv('data.csv',index=False)

In [28]:
df = pd.read_csv('data.csv')
print(df)

      name  age  salary department
0    ahmed   24  8000.0         it
1  mohamed   22  5000.0         hr
2  mahmoud   26  9000.0         it
3      ali   32  4700.0    finance
4    samir   30     NaN         hr

In [29]:
df['bonus'] = [700,500,600,400,300]

In [30]:
print(df)

      name  age  salary department  bonus
0    ahmed   24  8000.0         it    700
1  mohamed   22  5000.0         hr    500
2  mahmoud   26  9000.0         it    600
3      ali   32  4700.0    finance    400
4    samir   30     NaN         hr    300

In [31]:
df.to_csv('data.csv',index=False)

In [32]:
df['salary_after_bonus'] = df['salary'] + df['bonus']

In [33]:
df.to_csv('data.csv',index=False)

In [34]:
df.head()

      name  age  salary department  bonus  salary_after_bonus
0    ahmed   24  8000.0         it    700              8700.0
1  mohamed   22  5000.0         hr    500              5500.0
2  mahmoud   26  9000.0         it    600              9600.0
3      ali   32  4700.0    finance    400              5100.0
4    samir   30     NaN         hr    300                 NaN

In [35]:
import numpy as np

df['salary_level'] = np.where(
    df['salary'] >= 6000,'High','Low'
)

In [36]:
df.head()

      name  age  salary department  bonus  salary_after_bonus salary_level
0    ahmed   24  8000.0         it    700              8700.0         High
1  mohamed   22  5000.0         hr    500              5500.0          Low
2  mahmoud   26  9000.0         it    600              9600.0         High
3      ali   32  4700.0    finance    400              5100.0          Low
4    samir   30     NaN         hr    300                 NaN          Low

In [37]:
## sorting data
df = df.sort_values(
    by='salary',
    ascending=False
)

In [38]:
df.head()

      name  age  salary department  bonus  salary_after_bonus salary_level
2  mahmoud   26  9000.0         it    600              9600.0         High
0    ahmed   24  8000.0         it    700              8700.0         High
1  mohamed   22  5000.0         hr    500              5500.0          Low
3      ali   32  4700.0    finance    400              5100.0          Low
4    samir   30     NaN         hr    300                 NaN          Low

In [39]:
df.isnull().sum()

name                  0
age                   0
salary                1
department            0
bonus                 0
salary_after_bonus    1
salary_level          0
dtype: int64

In [40]:
df["salary"] = df["salary"].fillna(
    df["salary"].mean()
)

In [41]:
df.isnull().sum()

name                  0
age                   0
salary                0
department            0
bonus                 0
salary_after_bonus    1
salary_level          0
dtype: int64

In [42]:
df.head()

      name  age  salary department  bonus  salary_after_bonus salary_level
2  mahmoud   26  9000.0         it    600              9600.0         High
0    ahmed   24  8000.0         it    700              8700.0         High
1  mohamed   22  5000.0         hr    500              5500.0          Low
3      ali   32  4700.0    finance    400              5100.0          Low
4    samir   30  6675.0         hr    300                 NaN          Low

In [43]:
df['salary_after_bonus'][4] = 6975.0

C:\Users\ahmed\AppData\Local\Temp\ipykernel_20644\1661086063.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['salary_after_bonus'][4] = 6975.0
C:\Users\ahmed\AppData\Local\Temp\ipykernel_20644\1661086063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary_after_bonus'][4] = 6975.0

In [44]:
df.head()

      name  age  salary department  bonus  salary_after_bonus salary_level
2  mahmoud   26  9000.0         it    600              9600.0         High
0    ahmed   24  8000.0         it    700              8700.0         High
1  mohamed   22  5000.0         hr    500              5500.0          Low
3      ali   32  4700.0    finance    400              5100.0          Low
4    samir   30  6675.0         hr    300              6975.0          Low

In [45]:
df.to_csv('data.csv',index=False)