In [3]:
import pandas as pd
import numpy as np

arr = np.array([[20,5000],[30,7000]])
df = pd.DataFrame({
    'age' : [20,30],
    'salary' : [5000,7000]
})
ser = pd.Series([1,2],index=['ahmed','mohamed'])
print(arr)
print(df)
print(ser)

[[  20 5000]
 [  30 7000]]
   age  salary
0   20    5000
1   30    7000
ahmed      1
mohamed    2
dtype: int64

In [5]:
scores = pd.Series(
    [90, 85, 70],
    index=["Ahmed", "Mohamed", "Ali"]
)

print(scores)
print(scores.iloc[0])
print(scores.loc['Ahmed'])

Ahmed      90
Mohamed    85
Ali        70
dtype: int64
90
90

In [8]:
data = {
    "name": ["Ahmed", "Mohamed", "Ali"],
    "age": [24, 30, 28],
    "salary": [5000, 7000, 6000]
}

df = pd.DataFrame(data)

print(df)
print(df.columns)
print(df.columns.tolist())

      name  age  salary
0    Ahmed   24    5000
1  Mohamed   30    7000
2      Ali   28    6000
Index(['name', 'age', 'salary'], dtype='object')
['name', 'age', 'salary']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [10]:
df.head()

      name  age  salary
0    Ahmed   24    5000
1  Mohamed   30    7000
2      Ali   28    6000

In [11]:
df.tail(2)

      name  age  salary
1  Mohamed   30    7000
2      Ali   28    6000

In [12]:
df.describe()

             age  salary
count   3.000000     3.0
mean   27.333333  6000.0
std     3.055050  1000.0
min    24.000000  5000.0
25%    26.000000  5500.0
50%    28.000000  6000.0
75%    29.000000  6500.0
max    30.000000  7000.0

In [13]:
result = df[df["age"] > 25]

print(result)

      name  age  salary
1  Mohamed   30    7000
2      Ali   28    6000

In [15]:
df = pd.DataFrame({
    "name": ["Ahmed", "Mohamed", "Ali"],
    "age": [24, None, 28]
})
print(df.isnull())
print(df.isnull().sum())

    name    age
0  False  False
1  False   True
2  False  False
name    0
age     1
dtype: int64